### PR TITLE
Support RSpec 3

### PR DESCRIPTION
**Pull request by junaruga**
I would send patch to use RSpec3.

Let me check the result of Travis with this PR, as I fixed mostly, but still not perfect (2 failures)
I want to know whether the 2 failures depend on Ruby version or not, as I am using new version Ruby 2.4.0.

```
$ ruby -v
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

$ bundle -v
Bundler version 1.14.3

$ bundle install --path vendor/bundle

$ bundle list
Gems included by the bundle:
  * bundler (1.14.3)
  * daemons (1.2.4)
  * diff-lcs (1.3)
  * eventmachine (1.2.3)
  * rack (2.0.1)
  * rake (12.0.0)
  * rake-compiler (1.0.3)
  * rspec (3.5.0)
  * rspec-core (3.5.4)
  * rspec-expectations (3.5.0)
  * rspec-mocks (3.5.0)
  * rspec-support (3.5.0)
  * thin (1.7.0)

$ bundle exec rake spec
...
[2017-03-02T22:11:15.056429 #17551]  INFO -- : Hey
[2017-03-02T22:11:15.065435 #17551]  INFO -- : hey
...
Failures:

  1) Thin::Logging tracing routines (with NO custom logger) should emit trace messages if tracing is enabled 
     Failure/Error: out.include?("Hey").should be_truthy
     
       expected: truthy value
            got: false
     # ./spec/logging_spec.rb:158:in `block (3 levels) in <top (required)>'

  2) Thin::Logging tracing routines (with NO custom logger) should be usable (at the module level) for logging
     Failure/Error: out.include?("hey").should be_truthy
     
       expected: truthy value
            got: false
     # ./spec/logging_spec.rb:167:in `block (3 levels) in <top (required)>'
...
197 examples, 2 failures
```

Thanks.

### CODE REVIEW

**Comment by junaruga** [comment]
Could you please activate Travis CI?

https://travis-ci.org/macournoyer/thin
> This is not an active repository
> You don't have sufficient rights to enable this repo on Travis.
> Please contact the admin to enable it or to receive admin rights yourself.

**Comment by junaruga** [comment]
As a reference, when I ran above 2 failed tests individually, they were succeeded.

```
$ bundle exec rspec spec/logging_spec.rb -e "should emit trace messages if tracing is enabled " --format documentation
...
Thin::Logging
  tracing routines (with NO custom logger)
    should emit trace messages if tracing is enabled
...
1 example, 0 failures
```

```
$ bundle exec rspec spec/logging_spec.rb:161 --format documentation
...
Thin::Logging
  tracing routines (with NO custom logger)
    should be usable (at the module level) for logging
...
1 example, 0 failures
```

**Comment by ioquatix** [comment]
@junaruga for the sake of people who still use this server, do you have time to rebase these changes on master? I'm going to set up github actions if possible.

**Comment by junaruga** [comment]
@ioquatix let me rebase it. Thanks for the working to set up the github actions!

**Comment by ioquatix** [comment]
I cannot get daemonization specs to pass. I don't understand how it's failing on GH Actions. I'm going to merge anyway.

Then can you rebase? Then, we can try to fix flaky specs.

**Comment by ioquatix** [comment]
The way the state is managed in `daemonizing_spec.rb` is super bad. There is tons of state leaking from one spec to the next. The way the processes are killed in the after hook is wrong - those processes could already be dead so it could just be killing random processes unrelated to testing.

**Comment by junaruga** [comment]
> Then can you rebase? Then, we can try to fix flaky specs.

Yes, I can. I try to do it today.

**Comment by junaruga** [comment]
Reased. I removed `.travis.yml`, as it was removed on the current master branch.

> I cannot get daemonization specs to pass.

I also observed the daemonization spec did not pass on the current latest master branch before rebasing.
But after rebasing on feature/rspec3 on the master branch, the spec passed on my local.

Instead of that, I saw the following 2 `Thin::Logging tracing routines (with NO custom logger)` specs failed.

```
  1) Thin::Logging tracing routines (with NO custom logger) should emit trace messages if tracing is enabled-
     Failure/Error: out.include?("Hey").should be_truthy

       expected: truthy value
            got: false
     # ./spec/logging_spec.rb:158:in `block (3 levels) in <top (required)>'

  2) Thin::Logging tracing routines (with NO custom logger) should be usable (at the module level) for logging
     Failure/Error: out.include?("hey").should be_truthy

       expected: truthy value
            got: false
     # ./spec/logging_spec.rb:167:in `block (3 levels) in <top (required)>'
```

`@object.trace` and `Logging.trace_msg` are methods to output the message when `Logging.trace?` is `true`.


The 2 spec passed when it was executed as isolated test.

```
$ bundle exec rspec spec/logging_spec.rb:158

$ bundle exec rspec spec/logging_spec.rb:167
```

The 2 specs still failed when running like this.

```
$ bundle exec rspec spec/logging_spec.rb
```

But when adding the following code, as a sub consequence (?), the 2 spec passed on my local when running `bundle exec rspec spec/logging_spec.rb`. :-)

```
$ git diff
diff --git a/spec/logging_spec.rb b/spec/logging_spec.rb
index 9510c1f..d38f005 100644
--- a/spec/logging_spec.rb
+++ b/spec/logging_spec.rb
@@ -151,7 +151,9 @@ describe Logging do
 
     it "should emit trace messages if tracing is enabled " do
       Logging.trace = true
+      p "[DEBUG] Hey trace: #{Logging.trace?}"
       out = with_redirected_stdout do
+        p "[DEBUG] Hey trace: #{Logging.trace?}"
         @object.trace("Hey")
       end
 
@@ -160,7 +162,9 @@ describe Logging do
 
     it "should be usable (at the module level) for logging" do
       Logging.trace = true
+      p "[DEBUG] hey trace: #{Logging.trace?}"
       out = with_redirected_stdout do
+        p "[DEBUG] hey trace: #{Logging.trace?}"
         Logging.trace_msg("hey")
       end
```



It's great if you take a look at the code.
Thanks.

**Comment by ioquatix** [comment]
I want to merge this, and now I'll take a look at why the specs are not passing.

**Pull request merged**
