### PR TITLE
remove eventmachine restriction

### PR DESCRIPTION
**Pull request by schmurfy**
Allow eventmachine 1.2 to be used.

### CODE REVIEW

**Comment by macournoyer** [comment]
Thanks!

**Comment by sodabrew** [comment]
Doesn't `~> 1.0` allow for any 1.x, version already? I've definitely had feedback from people who began using thin and eventmachine 1.2 after a `bundle update` with the existing code.

**Comment by macournoyer** [comment]
Yes indeed! I got confused again by the `~>`... :/

`~> 1.0` means >= to 1.0 but < 2.0.

I'm reverting this. Thanks for pointing this out @sodabrew !

**Comment by schmurfy** [comment]
looks like i got confused too, is the ~> already in the latest release ?
Because what got me there is that thin was keeping back eventmachine update :(

**Comment by macournoyer** [comment]
@schmurfy should be in v1.6.4: https://github.com/macournoyer/thin/commit/0770aa00399480bbd8ca7391d416c8700818e719

**Pull request merged**
